ame: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: actions-runners
    steps:
      - name: Check runner
        run: echo "Runner is working!"
